packages:
  - apps/*
  - packages/*
catalog:
  react: ^19.2.4
  react-dom: ^19.2.4
  "@types/react": ^19.2.13
  "@types/react-dom": ^19.0.2
  "@biomejs/biome": ^2.3.14
  '@types/node': ^25.2.3
  typescript: ^5.3.3
  tailwindcss: ^4.1.18
  "@tailwindcss/postcss": ^4.0.0
  postcss: ^8.5.6
  autoprefixer: ^10.4.24
  vitest: ^4.0.18
  zod: ^4.3.6
  '@vitejs/plugin-react': ^5.1.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - es5-ext
  - esbuild
  - sharp
