packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  "@types/react": ^18.2.64
  "@types/react-dom": ^18.2.21
  "@types/node": ^20.11.24
  typescript: ^5.3.3
  tailwindcss: ^3.4.1
  postcss: ^8.4.38
  autoprefixer: ^10.4.19
  vitest: ^1.2.1
  "@vitejs/plugin-react": ^4.2.1
