packages:
  - apps/*
  - packages/*
catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@biomejs/biome": ^2.3.9
  '@types/node': ^25.0.2
  typescript: ^5.3.3
  tailwindcss: ^4.1.18
  "@tailwindcss/postcss": ^4.0.0
  postcss: ^8.5.6
  autoprefixer: ^10.4.23
  vitest: ^4.0.16
  zod: ^4.2.1
  '@vitejs/plugin-react': ^5.1.2
onlyBuiltDependencies:
  - '@biomejs/biome'
  - es5-ext
  - esbuild
  - sharp
